#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define COMBO_TERM 25
#define COMBO_SHOULD_TRIGGER
#define IGNORE_MOD_TAP_INTERRUPT

// Cirque Touchpad Options
//#define CIRQUE_PINNACLE_DIAMETER_MM 35
//#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
//#define CIRQUE_PINNACLE_TAP_ENABLE
//#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
//#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
//#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_3X
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define FP_POINTING_SCROLLING_DPI 1
#define FP_POINTING_SCROLLING_MIN_DPI 1
#define FP_POINTING_SCROLLING_MAX_DPI 2

// Trackball Options
#define FP_POINTING_DEFAULT_DPI 25
#define FP_POINTING_MIN_DPI 5
#define FP_POINTING_MAX_DPI 75
#define FP_POINTING_ACCELERATION_ENABLE
#define FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY 25


#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 6
#define AUTO_MOUSE_TIME 500
#define AUTO_MOUSE_DELAY 750

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
